tools/furikaeri-1.0.2/config/routes.rb
Rails.application.routes.draw do
  resources :projects, only: [:new, :create, :show], param: :key, path: '' do
    resources :issues, only: [:create, :destroy]
  end
  root to: 'pages#top'
end

tools/furikaeri-1.0.2/app/models/issue.rb
class Issue < ActiveRecord::Base
  extend Enumerize

  KPT = %w(keep problem try)
  enumerize :status, in: KPT, scope: true, default: KPT.first

  validates :title, presence: true
  belongs_to :project
end

tools/furikaeri-1.0.2/app/models/project.rb
class Project < ActiveRecord::Base
  validates :name, presence: true
  validates :key, uniqueness: true
  before_validation :set_key
  has_many :issues, dependent: :destroy

  def to_param
    key
  end

  private

  def set_key
    self.key = SecureRandom.hex
  end
end

tools/furikaeri-1.0.2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

tools/furikaeri-1.0.2/app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :set_project
  before_action :set_issue, only: [:destroy]
  before_action :set_new_issue, only: [:create]

  def create
    if @issue.save
      redirect_to :back, notice: 'created new issue'
    else
      redirect_to :back, notice: @issue.errors.full_messages.join(',')
    end
  end

  def destroy
    if @issue.destroy
      redirect_to :back, notice: 'deleted an issue'
    else
      redirect_to :back, notice: @issue.errors.full_messages.join(',')
    end
  end

  private

  def set_project
    @project = Project.find_by(key: params[:project_key])
  end

  def set_issue
    @issue = @project.issues.find(params[:id])
  end

  def set_new_issue
    @issue = @project.issues.build(issue_params)
  end

  def issue_params
    params.require(:issue).permit(:title, :status)
  end
end

tools/furikaeri-1.0.2/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def top
    @project = Project.first
  end
end

tools/furikaeri-1.0.2/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show]
  before_action :set_new_project, only: [:new, :create]

  def new
  end

  def create
    if @project.save
      redirect_to @project, notice: 'created new project'
    else
      render 'new'
    end
  end

  def show
  end

  private

  def set_project
    @project = Project.find_by(key: params[:key])
  end

  def set_new_project
    @project = Project.new(project_params)
  end

  def project_params
    params.fetch(:project, {}).permit(:name)
  end
end

tools/furikaeri-1.0.2/app/helpers/application_helper.rb
module ApplicationHelper
end

tools/furikaeri-1.0.2/app/views/issues/_form.html.haml
= form_for([project, issue]) do |f|
  = f.text_field(:title, placeholder: 'issue')
  = f.select(:status, Issue.status.options)
  = f.submit('+')

tools/furikaeri-1.0.2/app/views/issues/_issue.html.haml
= issue.title
= link_to(url_for([issue.project, issue]), method: :delete, class: 'delete-link') do
  x

tools/furikaeri-1.0.2/app/views/issues/_issues.html.haml
%ul{class: status}
  = content_tag_for(:li, issues.with_status(status)) do |issue|
    = render('issues/issue', issue: issue)

tools/furikaeri-1.0.2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Furikaeri</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= flash[:notice] %>
<%= yield %>

</body>
</html>

tools/furikaeri-1.0.2/app/views/pages/top.html.haml
= render('projects/project', project: @project)

tools/furikaeri-1.0.2/app/views/projects/_form.html.haml
= project.errors.full_messages.join(',')
= form_for(project) do |f|
  = f.text_field(:name, placeholder: 'project name')
  = f.submit

tools/furikaeri-1.0.2/app/views/projects/_project.html.haml
%h1
  = project.name
  %small
    = link_to '+', new_project_path, class: 'new-project-link'
= render('issues/form', project: project, issue: Issue.new)

%h2 Keep
= render('issues/issues', issues: project.issues, status: :keep)

%h2 Problem
= render('issues/issues', issues: project.issues, status: :problem)

%h2 Try
= render('issues/issues', issues: project.issues, status: :try)

tools/furikaeri-1.0.2/app/views/projects/new.html.haml
= render('form', project: @project)

tools/furikaeri-1.0.2/app/views/projects/show.html.haml
= render('projects/project', project: @project)